skpandey885/HealhUb

- pages/about.html
I have added some text in the privacy policy section.
> update privacy policy

- css/covidSection.css
- js/covidSecion.js
Fix : #9 
Made Responsive Table and Improved the stats for the table
https://atif0604.github.io/HealhUb/
> Made Responsive Table for Covid Data and Improved Stats

- css/covidSection.css
- pages/covidSection.html
Jwoc mentee
I improved the entire css of the website.
Issue: #17
Link:  https://soumali28.github.io/HealhUb/pages/covidSection.html
https://user-images.githubusercontent.com/66300439/152517598-b4938537-61dc-436d-b2a5-bdbc8e775075.mp4
> Improved the css of the website

- css/cards.css
- css/covidBlogs.css
- pages/cards.html
- pages/tips.html
https://tess-vanta.github.io/HealhUb/pages/cards.html
> Made the blog footer responsive

- css/covidSection.css
- pages/covidSection.html
**Issue No. #32**
Link to the website:  [https://tanya-gupta25.github.io/HealhUb/](url)
After changes this is how these boxes look like:-
> Added Do's & Dont's in different boxes and styled them

- css/homepage.css
- index.html
- pages/tools.html
Added preloader as per issue #14 
Live Preview :-
https://sabariganesh-k.github.io/HealhUb/
> Preloader added

- css/homepage.css
- index.html
As per the issue #55 
I improved the responsiveness of the preloader for any device
Live: https://srijita-mandal.github.io/HealhUb/
**Preview:**
Desktop view:
https://user-images.githubusercontent.com/84610348/153695640-18ab50ac-5dc8-4405-8e1d-6e65940a1a58.mp4
Mobile view:
https://user-images.githubusercontent.com/84610348/153695659-e1ac2134-690a-4be4-8318-f8de4404232e.mp4
> #55 - Improved the responsiveness of the Preloader

- css/tools.css
- pages/tips.html
- pages/tools.html
- fixed the design of navbar in tools page in accord with the other pages.
- commented the following code in head section.
https://user-images.githubusercontent.com/72697074/153638139-ff24b145-6bf1-4542-a349-e803fc677d53.mp4
> Fixed the design on navbar in tools page

- css/homepage.css
- index.html
As per the issue #59 
I added slide down animation after preloader on the home page
link: https://srijita-mandal.github.io/HealhUb/
preview:
https://user-images.githubusercontent.com/84610348/154205934-99a82447-88ce-4693-9203-1ec2518e9f9d.mp4
> #59 Added slide down animation

- Documentation/documentation.md
> #72 Added documentation

- css/tools.css
- pages/tools.html
Fixes: #83 
I have updated the responsiveness of Tools Page
> Tools Page Responsiveness

- pages/covidSection.html
> Updated covid blogs button

- css/covidSection.css
- pages/covidSection.html
Fixes: #92 
The changes made: 
1. Made the "Tips to protect yourself" section vertical for smaller screens and updated the button position.
2. The data overflow is now solved.
3. The AboutUs section in footer is now centered.
> Covid Page Updated

- css/about.css
- css/bmi.css
- css/bodyFat.css
- css/cards.css
- css/covidBlogs.css
- css/homepage.css
- css/hospitals.css
- css/medicalHelp.css
- css/team-members.css
- css/tips.css
- css/tools.css
- css/trainer.css
> Updated about us for all pages

- css/team-members.css
> Updated navbar responsiveness

- css/tips.css
- pages/tips.html
Fixes: #100 
The following changes were made:
- The hamburger menu was made functional
- The overall responsiveness was improved
> Tips page responsiveness

- css/covidSection.css
_**Issue No: #114**_
- Made font-size of covid footer as other pages
Preview : (https://tanya-gupta25.github.io/HealhUb/)
> Updated footer text size in covid page

- css/covidSection.css
Added the margin that was mentioned in the issue
> fix:#117 Add some margin✌️

- css/bmi.css
- js/bmi.js
- pages/bmi.html
Age and Gender do affect the BMI.
As children grow at different rates, there is a difference in females' and males' weight for the same height.
> Bmi page modify

- css/about.css
- css/bmi.css
- css/bodyFat.css
- css/calorie.css
- css/cards.css
- css/covidBlogs.css
- css/covidSection.css
- css/homepage.css
- css/hospitals.css
- css/medicalHelp.css
- css/team-members.css
- css/tips.css
- css/tools.css
- css/trainer.css
- index.html
- js/bmi.js
- pages/about.html
- pages/bmi.html
- pages/bodyFat.html
- pages/calorie.html
- pages/cards.html
- pages/covidBlogs.html
- pages/covidSection.html
- pages/hospitals.html
- pages/medicalHelp.html
- pages/team-members.html
- pages/tips.html
- pages/tools.html
- pages/trainer.html
Hey @skpandey885 This is pull request with reference to issue no #134.
I have made some minor changes in navbar and footer and a major change in BMI page. Some changes I made are listed below:
- Added styles in buttons on home page.
Before:-
After:-
- Added font awesome icons to navbar and added transition effect.
Before:-
After:-
- Added transition in the red underlines in footer. Now when we hover over it it changes it width.
Before:-
After:- (Expand on hover)
- Reformed the BMI page as there were some bugs in it. Also added styling by adding hover effect.
Before:- (Some data was not visible in desktop. Now I have added the data in the card itself.)
After:-
I have also added the link where you can see all the changes I hade made.
https://sumitkr2000.github.io/HealhUb/
Please merge my PR …
> Improved Frontend

- css/about.css
> updated issue #130
